# . 필요 라이브러리 호출하기

데이터 읽기에 필요한 라이브러리를 호출 해야 합니다. 
pandas, numpy 를 호출합니다.

In [4]:
#필요 라이브러리 호출
import pandas as pd
import numpy as np

# 2. 파일 읽기

해당 데이터를 받아 옵니다. pandas의 read_csv를 활용하여 필요 데이터를 불러옵니다.

In [36]:
#파일 불러오기
r = pd.read_csv('./data/wine.csv')
r

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5492,5492,5,7.7,0.150,0.29,1.3,0.029,10.0,64.0,0.99320,3.35,0.39,10.1,white
5493,5493,6,6.3,0.180,0.36,1.2,0.034,26.0,111.0,0.99074,3.16,0.51,11.0,white
5494,5494,7,7.8,0.150,0.34,1.1,0.035,31.0,93.0,0.99096,3.07,0.72,11.3,white
5495,5495,5,6.6,0.410,0.31,1.6,0.042,18.0,101.0,0.99195,3.13,0.41,10.5,white
5496,5496,6,7.0,0.350,0.17,1.1,0.049,7.0,119.0,0.99297,3.13,0.36,9.7,white

파일의 원본을 보존하는 것은 중요합니다. 따라서 불러온 파일을 copy를 활용하여 원본 데이터를 보존합니다.

In [37]:
r2=r.copy()
r2

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5492,5492,5,7.7,0.150,0.29,1.3,0.029,10.0,64.0,0.99320,3.35,0.39,10.1,white
5493,5493,6,6.3,0.180,0.36,1.2,0.034,26.0,111.0,0.99074,3.16,0.51,11.0,white
5494,5494,7,7.8,0.150,0.34,1.1,0.035,31.0,93.0,0.99096,3.07,0.72,11.3,white
5495,5495,5,6.6,0.410,0.31,1.6,0.042,18.0,101.0,0.99195,3.13,0.41,10.5,white
5496,5496,6,7.0,0.350,0.17,1.1,0.049,7.0,119.0,0.99297,3.13,0.36,9.7,white

### 불러온 파일을 확인합니다. 앞부분을 확인하고자 하면, head 뒷 부분을 확인해보고 싶으면 tail을 활용해보세요!

In [7]:
#head를 활용해보세요
r = pd.read_csv('./data/wine.csv').head()
r

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white

In [38]:
#tail을 활용해보세요
r = pd.read_csv('./data/wine.csv').tail()
r

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
5492,5492,5,7.7,0.15,0.29,1.3,0.029,10.0,64.0,0.99320,3.35,0.39,10.1,white
5493,5493,6,6.3,0.18,0.36,1.2,0.034,26.0,111.0,0.99074,3.16,0.51,11.0,white
5494,5494,7,7.8,0.15,0.34,1.1,0.035,31.0,93.0,0.99096,3.07,0.72,11.3,white
5495,5495,5,6.6,0.41,0.31,1.6,0.042,18.0,101.0,0.99195,3.13,0.41,10.5,white
5496,5496,6,7.0,0.35,0.17,1.1,0.049,7.0,119.0,0.99297,3.13,0.36,9.7,white

<데이터 변수 설명>

| 변수 | 설명
|---|---|
| index | 구분자 |
|  quality | 품질 |
| fixed acidity | 산도 |
| volatile acidity | 휘발성산 |
| citric acid | 시트르산 |
| residual sugar | 잔당 : 발효 후 와인 속에 남아있는 당분 |
| chlorides | 염화물 |
| free sulfur dioxide | 독립 이산화황 |
| total sulfur dioxide | 총 이산화황 |
| density | 밀도 |
| pH | 수소이온농도 |
| sulphates |  황산염 |
| alcohol | 도수 |
| type |  종류 |

# 3. 결측치 확인

pandas의 info를 통해 데이터의 형태와 각  column의 형태를 확인할 수 있습니다.

In [39]:
r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 5492 to 5496
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 5 non-null      int64
 1   quality               5 non-null      int64
 2   fixed acidity         5 non-null      float64
 3   volatile acidity      5 non-null      float64
 4   citric acid           5 non-null      float64
 5   residual sugar        5 non-null      float64
 6   chlorides             5 non-null      float64
 7   free sulfur dioxide   5 non-null      float64
 8   total sulfur dioxide  5 non-null      float64
 9   density               5 non-null      float64
 10  pH                    5 non-null      float64
 11  sulphates             5 non-null      float64
 12  alcohol               5 non-null      float64
 13  type                  5 non-null      object
dtypes: float64(11), int64(2), object(1)
memory usage: 692.0+ bytes

결측치의 총 개수를 확인할 수 있습니다. isnull과 sum을 활용해서 해당 데이터에 있는 결측치 가 총 몇개 인지를 확인 할 수 있습니다.

In [40]:
r.isnull().sum()

index                   0
quality                 0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
type                    0
dtype: int64

결측값을 다루는 방법은 두 가지가 있습니다. 결측치를 가진 행을 삭제하거나. 평균값 혹은 최빈값으로 대체하는 것입니다.

### 우선 데이터의 평균, 4분위수, 최소값, 최대값을 확인해보세요! describe을 활용해보세요!

In [41]:
r.describe()

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
count,5.000000,5.00000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,5494.000000,5.80000,7.08000,0.248000,0.294000,1.260000,0.037800,18.400000,97.600000,0.991964,3.168000,0.478000,10.520000
std,1.581139,0.83666,0.66106,0.122963,0.074364,0.207364,0.007791,10.212737,21.208489,0.001123,0.106864,0.146526,0.649615
min,5492.000000,5.00000,6.30000,0.150000,0.170000,1.100000,0.029000,7.000000,64.000000,0.990740,3.070000,0.360000,9.700000
25%,5493.000000,5.00000,6.60000,0.150000,0.290000,1.100000,0.034000,10.000000,93.000000,0.990960,3.130000,0.390000,10.100000
50%,5494.000000,6.00000,7.00000,0.180000,0.310000,1.200000,0.035000,18.000000,101.000000,0.991950,3.130000,0.410000,10.500000
75%,5495.000000,6.00000,7.70000,0.350000,0.340000,1.300000,0.042000,26.000000,111.000000,0.992970,3.160000,0.510000,11.000000
max,5496.000000,7.00000,7.80000,0.410000,0.360000,1.600000,0.049000,31.000000,119.000000,0.993200,3.350000,0.720000,11.300000

### column sulphates에 결측치를 가진 행을 모두 삭제 해보세요. dropna(how="any")를 활용해보세요!

- 특정 칼럼에만 nan값이 있는지 확인하고 있을 경우, subset을 이용한다.
- how = "all" : 특정 행의 모든 값이 널값이어야 삭제한다.
- how = "any" : 특정 행에서 널값이 하나라도 있으면 삭제한다.

In [42]:
r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 5492 to 5496
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 5 non-null      int64
 1   quality               5 non-null      int64
 2   fixed acidity         5 non-null      float64
 3   volatile acidity      5 non-null      float64
 4   citric acid           5 non-null      float64
 5   residual sugar        5 non-null      float64
 6   chlorides             5 non-null      float64
 7   free sulfur dioxide   5 non-null      float64
 8   total sulfur dioxide  5 non-null      float64
 9   density               5 non-null      float64
 10  pH                    5 non-null      float64
 11  sulphates             5 non-null      float64
 12  alcohol               5 non-null      float64
 13  type                  5 non-null      object
dtypes: float64(11), int64(2), object(1)
memory usage: 692.0+ bytes

In [31]:
r.dropna(subset=["sulphates"], how='any', axis=0, inplace=True) 
r

,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,0,5,5.6,0.695,0.06,6.8,0.042,9.0,84.0,0.99432,3.44,0.44,10.2,white
1,1,5,8.8,0.610,0.14,2.4,0.067,10.0,42.0,0.99690,3.19,0.59,9.5,red
2,2,5,7.9,0.210,0.39,2.0,0.057,21.0,138.0,0.99176,3.05,0.52,10.9,white
3,3,6,7.0,0.210,0.31,6.0,0.046,29.0,108.0,0.99390,3.26,0.50,10.8,white
4,4,6,7.8,0.400,0.26,9.5,0.059,32.0,178.0,0.99550,3.04,0.43,10.9,white
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5492,5492,5,7.7,0.150,0.29,1.3,0.029,10.0,64.0,0.99320,3.35,0.39,10.1,white
5493,5493,6,6.3,0.180,0.36,1.2,0.034,26.0,111.0,0.99074,3.16,0.51,11.0,white
5494,5494,7,7.8,0.150,0.34,1.1,0.035,31.0,93.0,0.99096,3.07,0.72,11.3,white
5495,5495,5,6.6,0.410,0.31,1.6,0.042,18.0,101.0,0.99195,3.13,0.41,10.5,white
5496,5496,6,7.0,0.350,0.17,1.1,0.049,7.0,119.0,0.99297,3.13,0.36,9.7,white

### 남은 결측치의 값들을 각각의 평균 값으로 대체합니다! <br>
3-1. 먼저 각 열의 평균 값을 변수로 만듭니다. <br>
3-2. 다음으로 fillna를 활용하여 결측치의 값을 평균 값으로 대체합니다.

axis=0은 각 열의 모든 행에 대해서 동작합니다. 

  - drop 각 열의 행을 지운다

  - mean 각 열의 요소(행)들의 평균을 구한다.

  - rank 각 열의 요소(행)들의 순위를 구한다.

 

axis=1은 각 행의 모든 열에 대해서 동작합니다.

 - drop 각 행의 열을 지운다.

 - mean 각 행의  요소(열)들의 평균을 구한다.

 - rank 각 행의 요소(열)들의 순위를 구한다

In [43]:
# 3-1 null 값이 있는 column의 평균값을 구합니다!
r.replace("?", np.nan, inplace=True)
r
m=r.mean(axis=0)
m

C:\Users\82109\AppData\Local\Temp\ipykernel_26252\1237891583.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  m=r.mean(axis=0)

index                   5494.000000
quality                    5.800000
fixed acidity              7.080000
volatile acidity           0.248000
citric acid                0.294000
residual sugar             1.260000
chlorides                  0.037800
free sulfur dioxide       18.400000
total sulfur dioxide      97.600000
density                    0.991964
pH                         3.168000
sulphates                  0.478000
alcohol                   10.520000
dtype: float64

In [33]:
#3-2 결측치가 있는 각 컬럼의 값을 3-1에서 구한 mean으로 대체합니다. fillna를 활용해보세요!
r=r.fillna(r.mean(), inplace=True)
r

C:\Users\82109\AppData\Local\Temp\ipykernel_26252\3879594939.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  r=r.fillna(r.mean(), inplace=True)

In [44]:
r.isnull().sum()

index                   0
quality                 0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
type                    0
dtype: int64

In [45]:
r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 5492 to 5496
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 5 non-null      int64
 1   quality               5 non-null      int64
 2   fixed acidity         5 non-null      float64
 3   volatile acidity      5 non-null      float64
 4   citric acid           5 non-null      float64
 5   residual sugar        5 non-null      float64
 6   chlorides             5 non-null      float64
 7   free sulfur dioxide   5 non-null      float64
 8   total sulfur dioxide  5 non-null      float64
 9   density               5 non-null      float64
 10  pH                    5 non-null      float64
 11  sulphates             5 non-null      float64
 12  alcohol               5 non-null      float64
 13  type                  5 non-null      object
dtypes: float64(11), int64(2), object(1)
memory usage: 692.0+ bytes

## 전처리를 거친 데이터의 index는 무작위로 섞여 이후 모델링이나. 통계 적용에서 error가 발생할 수 있습니다. 따라서 reset_index를 활용하여 index를 재정렬합니다.

In [46]:
r.reset_index()

,level_0,index,quality,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,type
0,5492,5492,5,7.7,0.15,0.29,1.3,0.029,10.0,64.0,0.99320,3.35,0.39,10.1,white
1,5493,5493,6,6.3,0.18,0.36,1.2,0.034,26.0,111.0,0.99074,3.16,0.51,11.0,white
2,5494,5494,7,7.8,0.15,0.34,1.1,0.035,31.0,93.0,0.99096,3.07,0.72,11.3,white
3,5495,5495,5,6.6,0.41,0.31,1.6,0.042,18.0,101.0,0.99195,3.13,0.41,10.5,white
4,5496,5496,6,7.0,0.35,0.17,1.1,0.049,7.0,119.0,0.99297,3.13,0.36,9.7,white